# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Unframewindow(object):
    def setupUi(self, Unframewindow):
        Unframewindow.setObjectName("Unframewindow")
        Unframewindow.setWindowModality(QtCore.Qt.NonModal)
        Unframewindow.resize(1120, 639)
        Unframewindow.setMouseTracking(True)
        Unframewindow.setStatusTip("")
        Unframewindow.setAutoFillBackground(False)
        Unframewindow.setStyleSheet("QListWidget, QListView, QTreeWidget, QTreeView {\n"
"    outline: 0px;\n"
"}\n"
"\n"
"QListWidget {\n"
"    \n"
"    color: #cccccc;\n"
"    background: #2e2e36;\n"
"}\n"
"\n"
"QListWidget::Item:selected {\n"
"    background: #26262e;\n"
"    color: #fd7e19;\n"
"    border-left: 5px solid #fd9536;\n"
"    \n"
"}\n"
"HistoryPanel:hover {\n"
"    background: rgb(52, 52, 52);\n"
"}\n"
"/**********Title**********/\n"
"QTitleLabel{\n"
"        background-color: Gainsboro;\n"
"        font: 100 10pt;\n"
"}\n"
"\n"
"\n"
"/**********Button**********/\n"
"QTitleButton{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: black;\n"
"    border: 0px;\n"
"    font: 100 10pt;\n"
"}\n"
"QTitleButton#MinButton:hover,#MaxButton:hover{\n"
"    background-color: #D0D0D1;\n"
"    border: 0px;\n"
"    font: 100 10pt;\n"
"\n"
"\n"
"}\n"
"\n"
"QTitleButton#CloseButton:hover{\n"
"    background-color: #D32424;\n"
"    color: white;\n"
"    border: 0px;\n"
"    font: 100 10pt;\n"
"    \n"
"}\n"
"\n"
"QTitleButton#MinButton{\n"
"    image: url(./resource/short.png);\n"
"    \n"
"}\n"
"QTitleButton#CloseButton{\n"
"     image: url(./resource/exit.png);\n"
"}\n"
"QTitleButton#MaxButton{\n"
"     image: url(./resource/restore.png);\n"
"}\n"
"\n"
"\n"
"")
        Unframewindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(Unframewindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.left = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left.sizePolicy().hasHeightForWidth())
        self.left.setSizePolicy(sizePolicy)
        self.left.setMinimumSize(QtCore.QSize(150, 0))
        self.left.setMaximumSize(QtCore.QSize(150, 16777215))
        self.left.setMouseTracking(True)
        self.left.setStyleSheet("background: #2e2e36;")
        self.left.setObjectName("left")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.left)
        self.verticalLayout.setContentsMargins(0, 10, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.icon_1 = QtWidgets.QLabel(self.left)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon_1.sizePolicy().hasHeightForWidth())
        self.icon_1.setSizePolicy(sizePolicy)
        self.icon_1.setMinimumSize(QtCore.QSize(150, 100))
        self.icon_1.setMaximumSize(QtCore.QSize(150, 100))
        self.icon_1.setMouseTracking(True)
        self.icon_1.setStyleSheet("image: url(:/icon/resources/识别图标.png);\n"
"\n"
"background-color: #2e2e36;")
        self.icon_1.setText("")
        self.icon_1.setWordWrap(False)
        self.icon_1.setObjectName("icon_1")
        self.verticalLayout.addWidget(self.icon_1)
        self.icon_bottom_label = QtWidgets.QLabel(self.left)
        self.icon_bottom_label.setMinimumSize(QtCore.QSize(120, 50))
        self.icon_bottom_label.setMaximumSize(QtCore.QSize(120, 50))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setBold(True)
        font.setWeight(75)
        self.icon_bottom_label.setFont(font)
        self.icon_bottom_label.setStyleSheet("background: #2e2e36;\n"
"color: #cccccc;\n"
"border-bottom:0.5px solid rgb(240, 240, 240,30%);\n"
"\n"
"")
        self.icon_bottom_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.icon_bottom_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.icon_bottom_label.setLineWidth(0)
        self.icon_bottom_label.setScaledContents(False)
        self.icon_bottom_label.setAlignment(QtCore.Qt.AlignCenter)
        self.icon_bottom_label.setObjectName("icon_bottom_label")
        self.verticalLayout.addWidget(self.icon_bottom_label, 0, QtCore.Qt.AlignHCenter)
        self.left_widget = QtWidgets.QListWidget(self.left)
        self.left_widget.setMinimumSize(QtCore.QSize(150, 0))
        self.left_widget.setMaximumSize(QtCore.QSize(150, 16777215))
        self.left_widget.setBaseSize(QtCore.QSize(0, 0))
        self.left_widget.setMouseTracking(True)
        self.left_widget.setStyleSheet("QListWidget, QListView, QTreeWidget, QTreeView {\n"
"    outline: 0px;\n"
"}\n"
"\n"
"QListWidget {\n"
"    \n"
"    color: #cccccc;\n"
"    background: #2e2e36;\n"
"}\n"
"\n"
"QListWidget::Item:selected {\n"
"    background: #26262e;\n"
"    color: #fd7e19;\n"
"    border-left: 5px solid #fd9536;\n"
"    \n"
"}\n"
"HistoryPanel:hover {\n"
"    background: rgb(52, 52, 52);\n"
"}")
        self.left_widget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.left_widget.setSelectionRectVisible(False)
        self.left_widget.setObjectName("left_widget")
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/test/resource/极速响应.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icon/test/resource/极速识别.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        item.setIcon(icon)
        self.left_widget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/test/resource/文字.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/icon/test/resource/文字 (1).png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        item.setIcon(icon1)
        self.left_widget.addItem(item)
        self.verticalLayout.addWidget(self.left_widget)
        self.horizontalLayout_2.addWidget(self.left)
        self.right_widget = QtWidgets.QWidget(self.centralwidget)
        self.right_widget.setObjectName("right_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.right_widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_widget = QtWidgets.QWidget(self.right_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_widget.sizePolicy().hasHeightForWidth())
        self.label_widget.setSizePolicy(sizePolicy)
        self.label_widget.setMinimumSize(QtCore.QSize(0, 40))
        self.label_widget.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_widget.setMouseTracking(True)
        self.label_widget.setStyleSheet("QWidget#label_widget{\n"
"    background-color: rgb(255, 255, 255);\n"
"    \n"
"\n"
"\n"
"}\n"
"")
        self.label_widget.setObjectName("label_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.label_widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.MinButton = QTitleButton(self.label_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MinButton.sizePolicy().hasHeightForWidth())
        self.MinButton.setSizePolicy(sizePolicy)
        self.MinButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.MinButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.MinButton.setMouseTracking(True)
        self.MinButton.setStyleSheet("QTitleButton#MinButton{\n"
"    \n"
"    \n"
"    image: url(:/icon/resources/short.png);\n"
"\n"
"}")
        self.MinButton.setText("")
        self.MinButton.setFlat(True)
        self.MinButton.setObjectName("MinButton")
        self.horizontalLayout.addWidget(self.MinButton)
        self.MaxButton = QTitleButton(self.label_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MaxButton.sizePolicy().hasHeightForWidth())
        self.MaxButton.setSizePolicy(sizePolicy)
        self.MaxButton.setMinimumSize(QtCore.QSize(40, 0))
        self.MaxButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.MaxButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.MaxButton.setMouseTracking(True)
        self.MaxButton.setStyleSheet("QTitleButton#MaxButton{\n"
"    \n"
"    image: url(:/icon/resources/restore.png);\n"
"\n"
"}")
        self.MaxButton.setText("")
        self.MaxButton.setFlat(True)
        self.MaxButton.setObjectName("MaxButton")
        self.horizontalLayout.addWidget(self.MaxButton)
        self.CloseButton = QTitleButton(self.label_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CloseButton.sizePolicy().hasHeightForWidth())
        self.CloseButton.setSizePolicy(sizePolicy)
        self.CloseButton.setMinimumSize(QtCore.QSize(40, 0))
        self.CloseButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.CloseButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CloseButton.setMouseTracking(True)
        self.CloseButton.setAutoFillBackground(False)
        self.CloseButton.setStyleSheet("QTitleButton#CloseButton{\n"
"    \n"
"    image: url(:/icon/resources/exit.png);\n"
"\n"
"}")
        self.CloseButton.setText("")
        self.CloseButton.setFlat(True)
        self.CloseButton.setObjectName("CloseButton")
        self.horizontalLayout.addWidget(self.CloseButton)
        self.verticalLayout_2.addWidget(self.label_widget)
        self.stack_page = QtWidgets.QStackedWidget(self.right_widget)
        self.stack_page.setMinimumSize(QtCore.QSize(0, 0))
        self.stack_page.setObjectName("stack_page")
        self.page = QtWidgets.QWidget()
        self.page.setStyleSheet("QWidget#page{\n"
"    background-color: rgb(245, 249, 252);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.page.setObjectName("page")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_show_camera_widget = QtWidgets.QWidget(self.page)
        self.label_show_camera_widget.setObjectName("label_show_camera_widget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.label_show_camera_widget)
        self.horizontalLayout_8.setContentsMargins(14, 14, 14, 14)
        self.horizontalLayout_8.setSpacing(15)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.tableWidget = QtWidgets.QTableWidget(self.label_show_camera_widget)
        self.tableWidget.setStyleSheet("QTableWidget#tableWidget{\n"
"    border:0.5px solid lightgray; \n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.horizontalLayout_8.addWidget(self.tableWidget)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget_2 = QtWidgets.QWidget(self.label_show_camera_widget)
        self.widget_2.setMaximumSize(QtCore.QSize(180, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem1)
        self.read_button = QtWidgets.QPushButton(self.widget_2)
        self.read_button.setMinimumSize(QtCore.QSize(180, 30))
        self.read_button.setMaximumSize(QtCore.QSize(180, 30))
        self.read_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.read_button.setStyleSheet("\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color: rgb(253, 149, 54);\n"
"    \n"
"}\n"
"QPushButton\n"
"{\n"
"    background-color: rgb(255, 161, 75);\n"
"    border-radius:10px;\n"
"    color: rgb(255, 255, 255);\n"
"    border: 0px;\n"
"    font: 9pt \"微软雅黑\"  ;\n"
"}\n"
"")
        self.read_button.setObjectName("read_button")
        self.verticalLayout_10.addWidget(self.read_button)
        self.curtailnum_layout = QtWidgets.QHBoxLayout()
        self.curtailnum_layout.setObjectName("curtailnum_layout")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setStyleSheet("QLabel{\n"
"    \n"
"    font: 8pt \"微软雅黑\";\n"
"\n"
"}")
        self.label_4.setObjectName("label_4")
        self.curtailnum_layout.addWidget(self.label_4)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.curtailnum_layout.addWidget(self.lineEdit_2)
        self.curtailnum_layout.setStretch(1, 1)
        self.verticalLayout_10.addLayout(self.curtailnum_layout)
        self.text_layout1 = QtWidgets.QHBoxLayout()
        self.text_layout1.setObjectName("text_layout1")
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        self.label_6.setStyleSheet("font: 8pt \"微软雅黑\";")
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.text_layout1.addWidget(self.label_6)
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setStyleSheet("QLabel{\n"
"    border:0px solid lightgray; \n"
"    image: url(:/icon/resources/停止.png);\n"
"}\n"
"")
        self.label_5.setText("")
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.text_layout1.addWidget(self.label_5)
        self.label_7 = QtWidgets.QLabel(self.widget_2)
        self.label_7.setEnabled(True)
        self.label_7.setStyleSheet("QLabel{\n"
"    border:0px solid lightgray; \n"
"    image: url(:/icon/resources/执行.png);\n"
"}\n"
"")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.text_layout1.addWidget(self.label_7)
        self.text_layout1.setStretch(1, 1)
        self.text_layout1.setStretch(2, 1)
        self.verticalLayout_10.addLayout(self.text_layout1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem2)
        self.verticalLayout_9.addWidget(self.widget_2)
        self.horizontalLayout_8.addLayout(self.verticalLayout_9)
        self.horizontalLayout_8.setStretch(0, 3)
        self.verticalLayout_7.addWidget(self.label_show_camera_widget)
        self.cam_pic = QtWidgets.QPushButton(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.cam_pic.sizePolicy().hasHeightForWidth())
        self.cam_pic.setSizePolicy(sizePolicy)
        self.cam_pic.setMinimumSize(QtCore.QSize(20, 20))
        self.cam_pic.setMaximumSize(QtCore.QSize(20, 20))
        self.cam_pic.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/图片.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cam_pic.setIcon(icon2)
        self.cam_pic.setFlat(True)
        self.cam_pic.setObjectName("cam_pic")
        self.verticalLayout_7.addWidget(self.cam_pic, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_7.setStretch(0, 1)
        self.stack_page.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setStyleSheet("QWidget{\n"
"    background-color: rgb(245, 249, 252);\n"
"}\n"
"")
        self.page_2.setObjectName("page_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_6.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget = QtWidgets.QWidget(self.page_2)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.r_bottom_widget = QtWidgets.QWidget(self.widget)
        self.r_bottom_widget.setStyleSheet("")
        self.r_bottom_widget.setObjectName("r_bottom_widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.r_bottom_widget)
        self.horizontalLayout_3.setContentsMargins(14, 14, 14, 14)
        self.horizontalLayout_3.setSpacing(15)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.text_widget = QtWidgets.QWidget(self.r_bottom_widget)
        self.text_widget.setStyleSheet("QWidget#text_widget{\n"
"    border:0.5px solid lightgray; \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"")
        self.text_widget.setObjectName("text_widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.text_widget)
        self.verticalLayout_5.setContentsMargins(11, -1, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.text_widget)
        self.label_3.setStyleSheet("font: 9pt \"微软雅黑\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-top:2px;\n"
"border-bottom:1px solid lightgray;\n"
"padding-bottom:8px ;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.text_widget)
        self.tableWidget_2.setStyleSheet("border:0px;\n"
"background-color: rgb(255, 255, 255);")
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.verticalLayout_5.addWidget(self.tableWidget_2)
        self.horizontalLayout_3.addWidget(self.text_widget)
        self.horizontalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.addWidget(self.r_bottom_widget)
        self.verticalLayout_3.setStretch(0, 3)
        self.verticalLayout_6.addWidget(self.widget)
        self.button_bottom = QtWidgets.QWidget(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_bottom.sizePolicy().hasHeightForWidth())
        self.button_bottom.setSizePolicy(sizePolicy)
        self.button_bottom.setObjectName("button_bottom")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.button_bottom)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.export_2 = QtWidgets.QWidget(self.button_bottom)
        self.export_2.setMinimumSize(QtCore.QSize(650, 120))
        self.export_2.setMaximumSize(QtCore.QSize(650, 120))
        self.export_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.export_2.setObjectName("export_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.export_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.export_2)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setStyleSheet("background-color: transparent;\n"
"font: 9pt \"微软雅黑\";\n"
"border: 0px;\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.widget_3 = QtWidgets.QWidget(self.export_2)
        self.widget_3.setMinimumSize(QtCore.QSize(350, 30))
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(8)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.widget_3)
        self.label_8.setMinimumSize(QtCore.QSize(0, 100))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_8.setStyleSheet("QWidget#label_8{\n"
"    border:0.5px solid gray; \n"
"    font:  \"微软雅黑\";\n"
"}\n"
"")
        self.label_8.setWordWrap(True)
        self.label_8.setIndent(1)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setStyleSheet("background-color: transparent;\n"
"font: 9pt \"微软雅黑\";\n"
"border: 0px;\n"
"")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.label_9 = QtWidgets.QLabel(self.widget_3)
        self.label_9.setStyleSheet("\n"
"\n"
"border: 0px;\n"
"font: 8pt \"微软雅黑\"  ;")
        self.label_9.setScaledContents(True)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_6.addWidget(self.label_9)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_5.addWidget(self.widget_3)
        self.horizontalLayout_5.setStretch(1, 1)
        self.horizontalLayout_4.addWidget(self.export_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.upload_pic_5 = QtWidgets.QPushButton(self.button_bottom)
        self.upload_pic_5.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upload_pic_5.sizePolicy().hasHeightForWidth())
        self.upload_pic_5.setSizePolicy(sizePolicy)
        self.upload_pic_5.setMinimumSize(QtCore.QSize(250, 45))
        self.upload_pic_5.setMaximumSize(QtCore.QSize(250, 45))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.upload_pic_5.setFont(font)
        self.upload_pic_5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.upload_pic_5.setStyleSheet("QPushButton:enabled\n"
"{\n"
"    background-color: rgb(255, 161, 75);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 0px;\n"
"    font: 11.5pt \"微软雅黑\"  ;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color: rgb(253, 149, 54);\n"
"    \n"
"}\n"
"\n"
"QPushButton:disabled\n"
"{\n"
"    /*背景颜色*/  \n"
"    background-color: lightgray;\n"
"    color: rgb(255, 255, 255);\n"
"    border: 0px;\n"
"    font: 11.5pt \"微软雅黑\"  ;\n"
"    \n"
"}")
        self.upload_pic_5.setFlat(False)
        self.upload_pic_5.setObjectName("upload_pic_5")
        self.horizontalLayout_4.addWidget(self.upload_pic_5)
        self.horizontalLayout_4.setStretch(2, 2)
        self.verticalLayout_6.addWidget(self.button_bottom)
        self.verticalLayout_6.setStretch(0, 1)
        self.stack_page.addWidget(self.page_2)
        self.verticalLayout_2.addWidget(self.stack_page)
        self.horizontalLayout_2.addWidget(self.right_widget)
        Unframewindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Unframewindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1120, 23))
        self.menubar.setObjectName("menubar")
        Unframewindow.setMenuBar(self.menubar)

        self.retranslateUi(Unframewindow)
        self.stack_page.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Unframewindow)

    def retranslateUi(self, Unframewindow):
        _translate = QtCore.QCoreApplication.translate
        Unframewindow.setWindowTitle(_translate("Unframewindow", "MainWindow"))
        self.icon_bottom_label.setText(_translate("Unframewindow", "<html><head/><body><p>异常流量检测系统</p></body></html>"))
        __sortingEnabled = self.left_widget.isSortingEnabled()
        self.left_widget.setSortingEnabled(False)
        item = self.left_widget.item(0)
        item.setText(_translate("Unframewindow", "流量提取"))
        item = self.left_widget.item(1)
        item.setText(_translate("Unframewindow", "流量鉴别"))
        self.left_widget.setSortingEnabled(__sortingEnabled)
        self.MinButton.setToolTip(_translate("Unframewindow", "最小化"))
        self.MaxButton.setToolTip(_translate("Unframewindow", "最大化"))
        self.CloseButton.setToolTip(_translate("Unframewindow", "关闭窗口"))
        self.read_button.setText(_translate("Unframewindow", "截取数据包"))
        self.label_4.setText(_translate("Unframewindow", "截取数量"))
        self.lineEdit_2.setText(_translate("Unframewindow", "400"))
        self.label_6.setText(_translate("Unframewindow", "程序未运行"))
        self.label_3.setText(_translate("Unframewindow", "识别结果"))
        self.label.setText(_translate("Unframewindow", "页面说明："))
        self.label_8.setText(_translate("Unframewindow", "<html><head/><body><p><span style=\" font-size:8pt;\">本页面用于展示截取流量的标签：</span></p><p><span style=\" font-size:8pt;\">（1）页面分别展示的是</span><span style=\" font-family:\'Arial\',\'sans-serif\'; font-size:8pt; color:#333333; background-color:#ffffff;\">源IP地址，源端口，目的IP地址，目的端口和传输层协议(对于协议而言，</span><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:8pt; color:#000000;\">6:TCP 17:UDP 1:ICMP)</span></p><p><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:8pt; color:#000000;\">（2）我们主要使用2个训练集，分别是ISCX 2012 和CIC-IDS 2017。</span></p><p><span style=\" font-size:8pt;\"><br/></span></p></body></html>"))
        self.label_2.setText(_translate("Unframewindow", "检测模型:"))
        self.label_9.setText(_translate("Unframewindow", "<html><head/><body><p>三种模型交替判断</p></body></html>"))
        self.upload_pic_5.setText(_translate("Unframewindow", "开始识别"))
from title import QTitleButton
import picture_rc
